version: '3'
services:
  backend:
    build:
      context: ./backend
    networks:
      - internal
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm start

networks:
  internal:
    driver: bridge